"""
app/memory/chroma.py

ChromaDB adapter for semantic vector storage and retrieval.

Rules (from plan.md):
- Do NOT store canonical text — only id, source, path as metadata.
- Embeddings are generated by app/memory/embeddings.py (sentence-transformers).
- All access goes through manager.py.
"""

from __future__ import annotations

from pathlib import Path

import chromadb
from chromadb import Collection

from app.core.config import get_settings
from app.core.logging import get_logger
from app.memory.embeddings import embed, embed_batch
from app.memory.schemas import SearchResult

logger = get_logger("memory.chroma")

_COLLECTION_NAME = "openvoice_memory"


class ChromaStore:
    """Wraps a ChromaDB persistent collection for semantic search."""

    def __init__(self) -> None:
        chroma_path = str(Path(get_settings().chroma_path).resolve())
        self._client = chromadb.PersistentClient(path=chroma_path)
        self._collection: Collection = self._client.get_or_create_collection(
            name=_COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )
        logger.info(
            "chroma_ready",
            path=chroma_path,
            collection=_COLLECTION_NAME,
            count=self._collection.count(),
        )

    # ------------------------------------------------------------------
    # Indexing
    # ------------------------------------------------------------------

    def index(
        self,
        doc_id: str,
        source: str,
        path: str,
        text: str,
    ) -> None:
        """Index a document for semantic search.

        Args:
            doc_id: Unique identifier (e.g. note slug or task UUID).
            source: Origin — "obsidian", "sqlite.tasks", "sqlite.events".
            path:   File path (for obsidian) or table/row reference.
            text:   The canonical text to embed. NOT stored in ChromaDB.
        """
        with logger.timed("chroma_index", doc_id=doc_id, source=source):
            vector = embed(text)
            self._collection.upsert(
                ids=[doc_id],
                embeddings=[vector],
                metadatas=[{"source": source, "path": path}],
            )

    def index_batch(
        self,
        docs: list[dict[str, str]],
    ) -> None:
        """Batch index multiple documents.

        Each dict must have: id, source, path, text.
        """
        if not docs:
            return

        ids = [d["id"] for d in docs]
        texts = [d["text"] for d in docs]
        metadatas = [{"source": d["source"], "path": d["path"]} for d in docs]

        with logger.timed("chroma_index_batch", count=len(docs)):
            vectors = embed_batch(texts)
            self._collection.upsert(
                ids=ids,
                embeddings=vectors,
                metadatas=metadatas,
            )

    def delete(self, doc_id: str) -> None:
        """Remove a document from the index."""
        with logger.timed("chroma_delete", doc_id=doc_id):
            self._collection.delete(ids=[doc_id])

    # ------------------------------------------------------------------
    # Retrieval
    # ------------------------------------------------------------------

    def search(self, query: str, n_results: int = 5) -> list[SearchResult]:
        """Semantic similarity search.

        Returns up to `n_results` SearchResult objects with source references.
        Canonical text is NOT stored here — callers should resolve content
        from the original source using the `path` field.
        """
        with logger.timed("chroma_search", query=query[:60], n=n_results):
            vector = embed(query)
            results = self._collection.query(
                query_embeddings=[vector],
                n_results=min(n_results, max(self._collection.count(), 1)),
                include=["metadatas", "distances"],
            )

        ids = results["ids"][0]
        metadatas = results["metadatas"][0]
        distances = results["distances"][0]

        search_results: list[SearchResult] = []
        for doc_id, meta, dist in zip(ids, metadatas, distances):
            # Cosine distance → similarity score: 1 - distance
            score = max(0.0, 1.0 - float(dist))
            search_results.append(
                SearchResult(
                    id=doc_id,
                    source=meta.get("source", "chroma"),
                    path=meta.get("path", ""),
                    title=doc_id,        # caller resolves full title from path
                    snippet="",          # caller resolves snippet from source
                    score=round(score, 4),
                )
            )

        return search_results
